### ISSUE TITLE
Links at beginning of Example 1 don't work

### ISSUE THREAD

**Issue by lmejn** [ACRF-Image-X-Institute/TopasOpt#57]
A few of the links in Example 1 don't work. 
1. Not a link https://github.com/ACRF-Image-X-Institute/TopasOpt/blob/cec23ce7c69b0d5bc9ff7cea0ec2a9c6acba75ab/docsrc/ApertureOptimisation.md?plain=1#L19
2. Link doesn't seem to lead to anywhere https://github.com/ACRF-Image-X-Institute/TopasOpt/blob/cec23ce7c69b0d5bc9ff7cea0ec2a9c6acba75ab/docsrc/ApertureOptimisation.md?plain=1#L33

**Comment by bwheelz36** [comment]
thanks Lars! fixed
