### ISSUE TITLE
G4Data and HeadlessMode

### ISSUE THREAD

**Issue by cvelten** [ACRF-Image-X-Institute/TopasOpt#68]
I would suggest to give an (optional) argument to set the Geant4 data directory. It is only suggested by the TOPAS instructions to put it into `~/G4Data` but one may very well put it somewhere else, especially for multi-user setups. Also, for macOS installs the instructions suggest `~/Applications/G4Data` by comparison.

Secondly, I would suggest to invoke `/path/to/topas/bin/topas` by prefixing it with `TOPAS_HEADLESS_MODE=1`, i.e.:
```
TOPAS_HEADLESS_MODE=1 /path/to/topas/bin/topas /path/to/file/fileX.topas
```
This will only set that env. var. for that invocation and it will make sure that no graphics or Qt window will be opened regardless of what is entered (maybe erroneously) inside the parameter files or an include file.

**Comment by bwheelz36** [comment]
Those are both good points, thanks! I hadn't even realized I had hard coded the G4data parameter.
